# Generated by Django 4.2.3 on 2023-07-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_school', '0002_courseowners'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('video1', models.FileField(blank=True, null=True, upload_to='')),
                ('video2', models.FileField(blank=True, null=True, upload_to='')),
                ('video3', models.FileField(blank=True, null=True, upload_to='')),
                ('video4', models.FileField(blank=True, null=True, upload_to='')),
                ('video5', models.FileField(blank=True, null=True, upload_to='')),
                ('video6', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
