# Generated by Django 4.2.3 on 2023-07-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_school', '0004_photogallery_date_videogallery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='type',
            field=models.CharField(choices=[('Rahbariyat', 'Rahbariyat'), ('Boshqa xodimlar', 'Boshqa xodimlar')], max_length=1000, null=True),
        ),
    ]
